### ISSUE TITLE
iron man gone missing

### ISSUE THREAD

**Issue by makc** [nmalex/renderfarm.js-three.js-editor#1]
as per https://discourse.threejs.org/t/renderfarm-js-server-side-photorealistic-rendering-of-threejs-scenes/12227/21:
![Screen Shot 2020-02-25 at 14 12 35 ](https://user-images.githubusercontent.com/242577/75251054-1e3ca780-57da-11ea-84ce-b116de0534c5.png)
[ironman.zip](https://github.com/nmalex/renderfarm.js-three.js-editor/files/4250150/ironman.zip)

**Comment by nmalex** [comment]
thanks @makc , I managed to reproduce it with some of my models too. The model is good, hence - first bug here.

**Comment by nmalex** [comment]
Your GLTF file had Bones and SkinnedMesh objects, that were ignored. I added support for these types and now it renders. Fixed.
